version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kate-s-bird
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/index/uploads
    ports:
      - "1196:1196"
    volumes:
      - ./static:/index/static
      - ./data:/index/data
    restart: unless-stopped